---
id: communication-gap-detector
version: 1
gap_type: communication
priority: low
enabled: true

triggers:
  - condition: "friction_clarifications > 2"
    extract:
      desired_capability: "Multiple clarifications needed - communication gap"
    confidence_boost: 0.25

  - condition: "raw_json contains 'misunderstood'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'that''s not what'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'let me clarify'"
    confidence_boost: 0.2

  - condition: "raw_json contains 'I meant'"
    confidence_boost: 0.2

min_confidence: 0.4

scope_inference:
  - if: "default"
    then: session
