---
id: context-gap-detector
version: 1
gap_type: context
priority: medium
enabled: true

triggers:
  - condition: "raw_json contains 'forgot'"
    extract:
      desired_capability: "regex: forgot ([^.]+)"
    confidence_boost: 0.25

  - condition: "raw_json contains 'lost track'"
    confidence_boost: 0.25

  - condition: "raw_json contains 'don''t remember'"
    confidence_boost: 0.25

  - condition: "raw_json contains 'what we decided'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'previous session'"
    confidence_boost: 0.25

  - condition: "raw_json contains 'earlier'"
    confidence_boost: 0.15

min_confidence: 0.35

scope_inference:
  - if: "session"
    then: session
  - if: "project"
    then: project
  - if: "default"
    then: project
