---
id: discovery-gap-detector
version: 1
gap_type: discovery
priority: low
enabled: true

triggers:
  - condition: 'raw_json contains "didn''t know"'
    extract:
      desired_capability: "regex: didn't know (?:about )?([^.]+)"
    confidence_boost: 0.3

  - condition: "raw_json contains 'just found out'"
    confidence_boost: 0.25

  - condition: 'raw_json contains "there''s a"'
    confidence_boost: 0.15

  - condition: "raw_json contains 'discovered'"
    confidence_boost: 0.2

  - condition: "raw_json contains 'turns out'"
    confidence_boost: 0.2

min_confidence: 0.4

scope_inference:
  - if: "default"
    then: global
