---
id: learning-gap-detector
version: 1
gap_type: learning
priority: low
enabled: true

triggers:
  - condition: "raw_json contains 'should remember'"
    confidence_boost: 0.35

  - condition: "raw_json contains 'keep forgetting'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'told you before'"
    confidence_boost: 0.35

  - condition: "raw_json contains 'already said'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'preference'"
    confidence_boost: 0.2

min_confidence: 0.4

scope_inference:
  - if: "project"
    then: project
  - if: "default"
    then: global
