---
id: recovery-gap-detector
version: 1
gap_type: recovery
priority: high
enabled: true

triggers:
  - condition: "raw_json contains 'stuck'"
    confidence_boost: 0.3

  - condition: 'raw_json contains "don''t know how to recover"'
    confidence_boost: 0.4

  - condition: 'raw_json contains "can''t proceed"'
    confidence_boost: 0.3

  - condition: "raw_json contains 'dead end'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'no way forward'"
    confidence_boost: 0.35

  - condition: "tool_success == 0"
    confidence_boost: 0.15

min_confidence: 0.4

scope_inference:
  - if: "default"
    then: global
