---
id: verification-gap-detector
version: 1
gap_type: verification
priority: medium
enabled: true

triggers:
  - condition: 'raw_json contains "can''t verify"'
    confidence_boost: 0.35

  - condition: 'raw_json contains "can''t test"'
    confidence_boost: 0.35

  - condition: "raw_json contains 'no way to check'"
    confidence_boost: 0.35

  - condition: "raw_json contains 'hope this works'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'unable to confirm'"
    confidence_boost: 0.3

  - condition: "raw_json contains 'not sure if'"
    confidence_boost: 0.2

min_confidence: 0.4

scope_inference:
  - if: "project"
    then: project
  - if: "default"
    then: global
